version: "3"

services:
  dashboardui:
    image: personal-streamlit-dash:latest
    networks:
      - traefik-public
    environment:
      TODOIST_API_KEY: "${TODOIST_API_KEY?Variable not set}"
      OPENAI_API_KEY: "${OPENAI_API_KEY?Variable not set}"
      NEWSAPI_API_KEY: "${NEWSAPI_API_KEY?Variable not set}"
      MAPQUEST_API_KEY: "${MAPQUEST_API_KEY?Variable not set}"
      STREAMLIT_APP_OUTPUT_DIR: "/app/data"
      NEWSAPI_CACHE_DIR: "/app/data/newsapi-cache"
      INITIAL_NAME: "${INITIAL_NAME?Variable not set}"
      INITIAL_PASSWORD: "${INITIAL_PASSWORD?Variable not set}"
      INITIAL_USERNAME: "${INITIAL_USERNAME?Variable not set}"
      INITIAL_EMAIL: "${INITIAL_EMAIL?Variable not set}"
    volumes:
      - appdata:/app/data
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.dashboard-ui-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.dashboard-ui-http.entrypoints=http
        - traefik.http.routers.dashboard-ui-http.middlewares=https-redirect
        - traefik.http.routers.dashboard-ui-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.dashboard-ui-https.entrypoints=https
        - traefik.http.routers.dashboard-ui-https.tls=true
        - traefik.http.routers.dashboard-ui-https.tls.certresolver=le
        - traefik.http.services.dashboard-ui.loadbalancer.server.port=8501

volumes:
  appdata: { }

networks:
  traefik-public:
    external: true
