version: "3"

services:
  dashboard-ui:
    image: personal-streamlit-dash:latest
    build:
      context: ./
    environment:
      TODOIST_API_KEY: "${TODOIST_API_KEY?Variable not set}"
      OPENAI_API_KEY: "${OPENAI_API_KEY?Variable not set}"
      NEWSAPI_API_KEY: "${NEWSAPI_API_KEY?Variable not set}"
      MAPQUEST_API_KEY: "${MAPQUEST_API_KEY?Variable not set}"
      STREAMLIT_APP_OUTPUT_DIR: "/app/data"
      NEWSAPI_CACHE_DIR: "/app/data/newsapi-cache"
      INITIAL_NAME: "${INITIAL_NAME?Variable not set}"
      INITIAL_PASSWORD: "${INITIAL_PASSWORD?Variable not set}"
      INITIAL_USERNAME: "${INITIAL_USERNAME?Variable not set}"
      INITIAL_EMAIL: "${INITIAL_EMAIL?Variable not set}"
    volumes:
      - ./src/Home.py:/app/Home.py
      - ./src/pages:/app/pages
      - ./local/streamlit_app_output:/app/data
    ports:
      - 9999:8501
