credentials:
  usernames:
    sully:
      email: sully@sadburger.com
      name: Sully
      password: "$2b$12$tjTR718b8h2Ol4b.63gTT.vv1kPHozwMU2VkY48etifyQcxEx9oHO"

cookie:
  expiry_days: 30
  key: UQxDWU+1o8hO/stY0nmeInWs6opuwSfgepJf5eaC # Must be string
  name: my_login_cookie
